"""alter email table

Revision ID: 3712e03e748d
Revises: 
Create Date: 2026-07-02 14:10:55.819072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3712e03e748d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('to_email', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('cc_email', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('template_name', sa.Enum('PORTFOLIO', 'WELCOME', 'OTP', name='template_name', schema='email'), nullable=False),
    sa.Column('attachments', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SENT', 'FAILED', name='status_type', schema='email'), nullable=False),
    sa.Column('provider_message_id', sa.String(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='email'
    )
    op.create_index(op.f('ix_email_email_record_next_retry_at'), 'email_record', ['next_retry_at'], unique=False, schema='email')
    op.create_index(op.f('ix_email_email_record_status'), 'email_record', ['status'], unique=False, schema='email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_email_record_status'), table_name='email_record', schema='email')
    op.drop_index(op.f('ix_email_email_record_next_retry_at'), table_name='email_record', schema='email')
    op.drop_table('email_record', schema='email')
    # ### end Alembic commands ###
